apiVersion: v1
kind: Service
metadata:
  name: my-express-app-service
  labels:
    app: my-express-app
spec:
  type: LoadBalancer  # 외부로 노출
  selector:
    app: my-express-app
  ports:
    - protocol: TCP
      port: 80  # 클러스터 외부에서 접근할 때 사용하는 포트
      targetPort: 3000  # 컨테이너 내부에서 사용하는 포트 (Node.js의 3000 포트)
